# Generated by Django 2.2 on 2024-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMbackend',
            fields=[
                ('EmployeeID_id', models.CharField(max_length=11)),
                ('DealStatus', models.CharField(choices=[('hang_up', 'Hang Up'), ('not_interested', 'Not Interested'), ('gate_keeper', 'Gate Keeper'), ('decision_maker', 'Decision Maker'), ('call_appointment', 'Call Appointment'), ('visit_appointment', 'Visit Appointment'), ('follow_up', 'Follow Up'), ('visited', 'Visited'), ('voice_mail', 'Voice Mail'), ('no_answer', 'No Answer')], default='hang_up', max_length=20)),
                ('ShopName', models.CharField(max_length=100)),
                ('Date', models.TextField()),
                ('CallDuration', models.TextField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Appointement_Date', models.TextField(blank=True, null=True)),
                ('OWname', models.CharField(blank=True, max_length=20, null=True)),
                ('OWnum', models.CharField(blank=True, max_length=15, null=True)),
                ('GKname', models.CharField(blank=True, max_length=20, null=True)),
                ('GKnum', models.CharField(blank=True, max_length=15, null=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('Shop_Status', models.CharField(choices=[('junk_lead', 'Junk Lead'), ('qualified', 'Qualified'), ('prospecting', 'Prospecting'), ('onboarded', 'Onboarded'), ('no_answer', 'No Answer')], default='junk_lead', max_length=20)),
                ('AutoId', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CRMbackend',
            },
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Post_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Postcode',
            },
        ),
        migrations.CreateModel(
            name='ShopInfoUnique4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.TextField()),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('competitor', models.TextField(blank=True, null=True)),
                ('saturday', models.CharField(blank=True, max_length=255, null=True)),
                ('sunday', models.CharField(blank=True, max_length=255, null=True)),
                ('monday', models.CharField(blank=True, max_length=255, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=255, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=255, null=True)),
                ('thursday', models.CharField(blank=True, max_length=255, null=True)),
                ('friday', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_status', models.CharField(blank=True, max_length=10, null=True)),
                ('menu', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Shopinfo_unique_4',
            },
        ),
    ]
