# Generated by Django 2.2 on 2024-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfoUnique4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.TextField()),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('competitor', models.TextField(blank=True, null=True)),
                ('saturday', models.CharField(blank=True, max_length=255, null=True)),
                ('sunday', models.CharField(blank=True, max_length=255, null=True)),
                ('monday', models.CharField(blank=True, max_length=255, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=255, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=255, null=True)),
                ('thursday', models.CharField(blank=True, max_length=255, null=True)),
                ('friday', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_status', models.CharField(blank=True, max_length=10, null=True)),
                ('menu', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Shopinfo_unique_4',
            },
        ),
    ]
