# Generated by Django 2.2 on 2024-06-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Post_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Postcode',
            },
        ),
    ]
