# Generated by Django 2.2 on 2024-06-24 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ShopInfoUnique4',
        ),
        migrations.AlterField(
            model_name='crmbackend',
            name='EmployeeID_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.EmployeeID'),
        ),
    ]
