# Generated by Django 2.2 on 2024-06-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMbackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.CharField(max_length=11)),
                ('DealStatus', models.CharField(max_length=20)),
                ('ShopName', models.CharField(max_length=100)),
                ('Date', models.TextField()),
                ('CallDuration', models.TextField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('AppointmentDate', models.TextField(blank=True, null=True)),
                ('OWname', models.CharField(blank=True, max_length=20, null=True)),
                ('OWnum', models.CharField(blank=True, max_length=15, null=True)),
                ('GKname', models.CharField(blank=True, max_length=20, null=True)),
                ('GKnum', models.CharField(blank=True, max_length=15, null=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('ShopStatus', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'CRMbackend',
            },
        ),
    ]
