# Generated by Django 2.2 on 2024-06-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20240624_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crmbackend',
            old_name='EmployeeID_id',
            new_name='EmployeeID',
        ),
    ]
