# Generated by Django 2.2 on 2024-06-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMbackend',
            fields=[
                ('EmployeeID', models.CharField(max_length=11)),
                ('DealStatus', models.CharField(max_length=20)),
                ('ShopName', models.CharField(max_length=100)),
                ('Date', models.TextField()),
                ('CallDuration', models.TextField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Appointement_Date', models.TextField(blank=True, null=True)),
                ('OWname', models.CharField(blank=True, max_length=20, null=True)),
                ('OWnum', models.CharField(blank=True, max_length=15, null=True)),
                ('GKname', models.CharField(blank=True, max_length=20, null=True)),
                ('GKnum', models.CharField(blank=True, max_length=15, null=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('Shop_Status', models.CharField(max_length=20)),
                ('AutoId', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CRMbackend',
            },
        ),
    ]
